#!/usr/bin/env bash

set -eo pipefail

### SET COLOR CODES ###
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
CYAN=$(tput setaf 6)
RESET=$(tput sgr0)

usage()
{
    echo "Usage: $0 <up|destroy>"
    exit 1
}

if [ $# -ne 1 ] ; then
    usage
else
    case $1 in
      up|destroy|do)
          oper=$1
      ;;
      *)
          usage
      ;;
    esac
fi

if [[ "$oper" == "up" ]]; then
    PS3="${CYAN}Select desired deployment: ${RESET}"
    deployments=("greenfield - Recommended for isolated test/POV deployments. Creates new network infrastructure, test workloads, and a public jump host" "brownfield - Recommended for prod deployments. Bring-your-own existing network infrastructure customizations + no workload/bastion creation")
    select deployment in "${deployments[@]}"
    do
        case $REPLY in
            1)
            echo "${GREEN}Greenfield deployment selected...${RESET}"
            echo "${YELLOW}**Caution** These deployments include test workloads and publicly accessible jump hosts and are intended primarily for lab/test environments${RESET}"
            echo ""
            deployment=greenfield
            break
            ;;
            2)
            echo "${GREEN}Brownfield deployment selected...${RESET}"
            deployment=brownfield
            break
            ;;
            *) 
            echo "${RED}Invalid response - choose a number${RESET}"
        esac
    done
fi

if [[ "$deployment" == "greenfield" ]]; then
    PS3="${CYAN}Select desired deployment type: ${RESET}"
    dtypes=(
        "Deploy 1 Cloud Connector in new VPC Networks"
        "Deploy 1 Cloud Connector in new VPC Networks w/ Cloud DNS for ZPA"
        "Deploy multiple Cloud Connectors + Load Balancer in new VPC Networks"
        "Deploy multiple CC + Load Balancer in new VPC Networks w/ Cloud DNS for ZPA"
        "Deploy Auto Scaling Cloud Connectors + Load Balancer in new VPC Networks"
        "Deploy Auto Scaling Cloud Connectors + Load Balancer in new VPC Networks w/ Cloud DNS for ZPA"
    )
    COLUMNS=12
    select greenfield_type in "${dtypes[@]}"
    do
        case $REPLY in
            1)
            echo "${GREEN}Deployment type base_1cc selected...${RESET}"
            dtype=base_1cc
            break
            ;;
            2)
            echo "${GREEN}Deployment type base_1cc_zpa selected...${RESET}"
            dtype=base_1cc_zpa
            break
            ;;
            3)
            echo "${GREEN}Deployment type base_cc_ilb selected...${RESET}"
            dtype=base_cc_ilb
            break
            ;;
            4)
            echo "${GREEN}Deployment type base_cc_ilb_zpa selected...${RESET}"
            dtype=base_cc_ilb_zpa
            break
            ;;
            5)
            echo "${GREEN}Deployment type base_cc_asg selected...${RESET}"
            dtype=base_cc_asg
            break
            ;;
            6)
            echo "${GREEN}Deployment type base_cc_asg_zpa selected...${RESET}"
            dtype=base_cc_asg_zpa
            break
            ;;
            *) 
            echo "${RED}Invalid response. Please enter a number selection${RESET}"
        esac
    done
elif [[ "$deployment" == "brownfield" ]]; then
    PS3="${CYAN}Select desired deployment type: ${RESET}"
    dtypes=(
        "Deploy multiple Cloud Connectors + Load Balancer in new or existing VPC Networks" 
        "Deploy Auto Scaling Cloud Connectors + Load Balancer in new or existing VPC Networks"
    )
    select brownfield_type in "${dtypes[@]}"
    do
        case $REPLY in
            1)
            echo "${GREEN}Deployment type cc_ilb selected...${RESET}"
            dtype=cc_ilb
            break
            ;;
            2)
            echo "${GREEN}Deployment type cc_asg selected...${RESET}"
            dtype=cc_asg
            break
            ;;
            *) 
            echo "${RED}Invalid response. Please enter a number selection${RESET}"
        esac
    done
else
    dtype=$dtype
fi

echo "Discovering processor architecture..."
archdetect=$(uname -m)

tversion=1.1.9
echo "Detecting OS..."
if [[ "$OSTYPE" == "linux"* ]]; then
    os_str=linux
    arch=amd64
    ostype=Linux
elif [[ "$OSTYPE" == "darwin"* && $archdetect == "arm64" ]]; then
    os_str=darwin
    arch=arm64
    ostype=MacOS_arm64
elif [[ "$OSTYPE" == "darwin"* ]]; then
    os_str=darwin
    arch=amd64
    ostype=MacOS
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    os_str=freebsd
    arch=amd64
    ostype=FreeBSD
    echo "FreeBSD support coming soon..."
    exit 1
else
    echo "${RED}Unsupported OS: $OSTYPE${RESET}"
    exit 1
fi
echo "${GREEN}OS is $ostype${RESET}"

dir=bin
echo "Creating a local $dir directory if not present..."
if [[ ! -e $dir ]]; then
    mkdir $dir
elif [[ ! -d $dir ]]; then
    echo "${RED}$dir already exists but is not a directory${RESET}" 1>&2
    exit 1
fi

echo "Checking GCP Environment Variables and Cloud Connector bootstrap requirements ..."
# if .zsecrc is not present we'll assume that GCO env was never set
gcp_location_default="us-central1"
project_id_default="cc-poc-host-project-01"

if [[ "$oper" == "up" && ! -e ./.zsecrc ]]; then
first_run="yes"
    for file in ./$dtype/credentials/*.json; do 
        json_lookup=$(basename ./$dtype/credentials/*.json)
        if [[ $json_lookup == "*.json" ]]; then
        echo "${YELLOW}The Service Account JSON file could not be found in the directory ${dtype}/credentials...${RESET}"
        read -r -p "${CYAN}Enter Google Cloud Project Credential JSON full file path: ${RESET}" manual_gcp_credentials
            manual_file_check=$manual_gcp_credentials
            if test -f "$manual_file_check"; then
                echo "${GREEN}JSON file: $manual_gcp_credentials will be used...${RESET}"
                gcp_credentials=$manual_gcp_credentials
            else
                echo "${RED}JSON path invalid. Please confirm filename and path are correct and re-run zsec...${RESET}"
                exit 1    
            fi

        else
            while true; do
            read -r -p "${CYAN}Service Account JSON file named ${json_lookup} identified in directory ${dtype}/credentials. Is this the correct JSON to use? (yes/no): ${RESET}" json_lookup_response
                case $json_lookup_response in 
                yes|y )
                    gcp_credentials=./credentials/$json_lookup
                    echo "${GREEN}Using $gcp_credentials for deployment...${RESET}"
                break
                ;;
                no|n )
                    read -r -p "${CYAN}Copy JSON file to $dtype/credentials/ and enter filename here (e.g. serviceaccountname.json): ${RESET}" json_manual_input
                    file_check=./$dtype/credentials/$json_manual_input
                    if test -f "$file_check"; then
                        echo "${GREEN}JSON name $json_manual_input will be used...${RESET}"
                        gcp_credentials=./credentials/$json_manual_input
                    else
                        echo "${RED}JSON does not exist by this name. Please confirm filename and path are correct and re-run zsec...${RESET}"
                        exit 1    
                    fi
                break
                ;;
                    * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
                esac
            done
        fi
    break
    done
    echo "export TF_VAR_credentials='$gcp_credentials'" >> .zsecrc

    while true; do
        read -r -p "${CYAN}Are you deploying Cloud Connector to a different Project than your (Host Project) VPC Networks? (yes/no): ${RESET}" project_response
        case $project_response in 
        yes|y )
            read -r -p "${CYAN}Enter Google Cloud Host Project ID [where VPC exists/will be deployed]: ${RESET}" host_project_id
            echo "export TF_VAR_project_host=$host_project_id" >> .zsecrc
            echo "${YELLOW}Note - by default terraform will use $host_project_id as its default provider Project${RESET}"
            read -r -p "${CYAN}Enter Google Cloud Service Project ID [where CC will be deployed]: ${RESET}" project_id
            project_id=${project_id:-$project_id_default}
            echo "export TF_VAR_project='$project_id'" >> .zsecrc
            echo "****************************"
            echo "${YELLOW}Make sure your Terraform Service Account has appropriate permissions to both $host_project_id and $project_id Projects${RESET}"
            echo "****************************"
        break
        ;;
        no|n )
            read -r -p "${CYAN}Enter Google Cloud Project ID [Default=$project_id_default]: ${RESET}" project_id
            project_id=${project_id:-$project_id_default}
            echo "export TF_VAR_project='$project_id'" >> .zsecrc
            echo "${GREEN}All terraform resources will be created in Project $project_id${RESET}"
        break
        ;;
        * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
        esac
    done

    # GCP Region Selection
    PS3="${CYAN}Select desired GCP region: ${RESET}"
    COLUMNS=$(tput cols)
    region_list=(
        "asia-east1"
        "asia-east2"
        "asia-northeast1"
        "asia-northeast2"
        "asia-northeast3"
        "asia-south1"
        "asia-south2"
        "asia-southeast1"
        "asia-southeast2"
        "australia-southeast1"
        "australia-southeast2"
        "europe-central2"
        "europe-north1"
        "europe-southwest1"
        "europe-west1"
        "europe-west2"
        "europe-west3"
        "europe-west4"
        "europe-west6"
        "europe-west8"
        "europe-west9"
        "europe-west12"
        "me-central1"
        "me-west1"
        "northamerica-northeast1"
        "northamerica-northeast2"
        "southamerica-east1"
        "southamerica-west1"
        "us-central1"
        "us-east1"
        "us-east4"
        "us-east5"
        "us-south1"
        "us-west1"
        "us-west2"
        "us-west3"
        "us-west4"
    )
    select region_selection in "${region_list[@]}"; do
        for region_choice in "${region_list[@]}"; do
            if [[ $region_choice == $region_selection ]]; then
                gcp_location=$region_selection
                echo "GCP region ${GREEN}$gcp_location${RESET} selected..."
                echo "export TF_VAR_region=${gcp_location}" >> .zsecrc
            break 2
            fi
        done
    done

    while [[ "$dtype" == "base"* && "$oper" == "up" ]]; do
    clientpublicip=$(curl -s ifconfig.me)
    echo "${YELLOW}greenfield deployments include a publicly accessible ssh bastion host...${RESET}"
    read -r -p "${CYAN}Your current public IP is ${clientpublicip}. Lock SSH access to this IP? [yes/no]: ${RESET}" bastion_response
        case $bastion_response in
        yes|y )
            echo "${GREEN}Updating Bastion NSG to permit SSH only from ${clientpublicip}...${RESET}"
            echo "export 'TF_VAR_bastion_ssh_allow_ip=[\"${clientpublicip}/32\"]'" >> .zsecrc
            useclientip=true
        break
        ;;
        no|n )
            useclientip=false
        break
        ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
        esac
    done

    if [[ "$useclientip" == "false" ]]; then
        while true; do
        read -r -p "${CYAN}Lock SSH access to a different IP address or range? \"no\" is open (0.0.0.0/0) [yes/no]: ${RESET}" changebastionip
            case $changebastionip in
            yes|y )
                read -r -p "${CYAN}Enter new IP Address or CIDR range (e.g. 2.2.2.2/32): ${RESET}" bastionipinput
                echo "export 'TF_VAR_bastion_ssh_allow_ip=[\"${bastionipinput}\"]'" >> .zsecrc
                if [[ $bastionipinput =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[1-9]))$ ]]
                    then
                    echo "${RED}$bastionipinput - IP/Netmask valid${RESET}"
                    else
                    echo "${RED}$bastionipinput is not valid IP CIDR format${RESET}"
                    echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
                    exit 1
                fi
            break
            ;;
            no|n )
                echo "${YELLOW}**Caution** SSH access permitted for all IP addresses...${RESET}"
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done
    fi

    cc_instance_size=small
    if [[ $cc_instance_size == "small" ]]; then
        PS3="${CYAN}Select desired GCP VM type for Cloud Connector: ${RESET}"
        vm_sizes=("n2-standard-2 (Recommended)" "e2-standard-2")
        select ccvm_instance_type in "${vm_sizes[@]}"
        do
            case $REPLY in
                1)
                echo "${GREEN}Cloud Connector VM type n2-standard-2 selected${RESET}"
                echo "export TF_VAR_ccvm_instance_type='n2-standard-2'" >> .zsecrc
                break
                ;;
                2)
                echo "${GREEN}Cloud Connector VM type $ccvm_instance_type selected${RESET}"
                echo "export TF_VAR_ccvm_instance_type='$ccvm_instance_type'" >> .zsecrc
                break
                ;;
                *) 
                echo "${RED}invalid response - choose a number${RESET}"
            esac
        done
    elif [[ $cc_instance_size == "medium" ]]; then
        echo ""
    elif [[ $cc_instance_size == "large" ]]; then
        echo ""
    else
        exit 1
    fi

    cc_vm_prov_url=''
    while [ -z "${cc_vm_prov_url}" ]; do
        read -r -p "${CYAN}Enter CC Provisioning URL (E.g. connector.zscaler.net/api/v1/provUrl?name=gcp_prov_url): ${RESET}" cc_vm_prov_url
    done
    echo "${GREEN}Provisioning URL entered is: $cc_vm_prov_url${RESET}"
    echo "${YELLOW}**Caution** Make sure this matches the CC Instance Size $cc_instance_size chosen...${RESET}"
    echo "export TF_VAR_cc_vm_prov_url='$cc_vm_prov_url'" >> .zsecrc

    PS3="${CYAN}Select vault storage method: ${RESET}"
    vaults=("GCP Secret Manager" "HashiCorp Vault")
    select vault in "${vaults[@]}"
    do
        case $REPLY in
            1)
            echo "${GREEN}GCP Secret Manager selected...${RESET}"
            vault="gcp"
            break
            ;;
            2)
            echo "${GREEN}HCP Vault selected...${RESET}"
            vault="hcp"
            echo "export TF_VAR_hcp_vault_enabled=true" >> .zsecrc
            break
            ;;
            *) 
            echo "${RED}invalid response - choose a number${RESET}"
        esac
    done

    if [[ $vault == "gcp" ]]; then
        read -r -p "${CYAN}Enter GCP Secrets Manager Secret Name from Secrets Manager (E.g. projects/$project_id/secrets/secret_name): ${RESET}" secret_name
        echo "${GREEN}Secret Manager name entered is: $secret_name${RESET}"
        echo "export TF_VAR_secret_name='$secret_name'" >> .zsecrc
    elif [[ $vault == "hcp" ]]; then
        echo "${YELLOW}***Zscaler supports GCP Auth Method with IAM-Type Auth Role***${RESET}"
        read -r -p "${CYAN}Enter Vault Address (E.g. https://vault-name.hashicorp.cloud:8200): ${RESET}" hcp_vault_address
        echo "${GREEN}Vault Address entered is: $hcp_vault_address${RESET}"
        echo "export TF_VAR_hcp_vault_address='$hcp_vault_address'" >> .zsecrc
        read -r -p "${CYAN}Enter Secret Path (E.g. /v1/admin/secret/data/zs-secrets): ${RESET}" hcp_vault_secret_path
        echo "${GREEN}Vault Secret Path entered is: $hcp_vault_secret_path${RESET}"
        echo "export TF_VAR_hcp_vault_secret_path='$hcp_vault_secret_path'" >> .zsecrc
        read -r -p "${CYAN}Enter HCP Vault Role Name (E.g. vault-iam-auth-role): ${RESET}" hcp_vault_role_name
        echo "${GREEN}Vault Role Name entered is: $hcp_vault_role_name${RESET}"
        echo "export TF_VAR_hcp_vault_role_name='$hcp_vault_role_name'" >> .zsecrc
    else
        echo "${RED}Unsupported vault type${RESET}"
        exit 1
    fi

    while true; do
    if [[ $vault == "hcp" ]]; then
        echo "${YELLOW}With HCP Vault, it is generally recommended to already have a Service Account created and authentication linked with GCP${RESET}"
    fi
    read -r -p "${CYAN}Do you have an existing Service Account in project $project_id to assign to Cloud Connector? (yes/no): ${RESET}" byo_ccvm_service_account_response
        case $byo_ccvm_service_account_response in 
        yes|y ) 
            echo "Using an existing Service Account..."
            read -r -p "${CYAN}Enter existing Service Account within the project ${GREEN}$project_id${RESET} (e.g. my-service): ${RESET}" byo_ccvm_service_account
            echo "${GREEN}You entered $byo_ccvm_service_account${RESET}"
            if [[ $vault == "hcp" ]]; then
                echo "${YELLOW}**Warning**${RESET} - As a prerequisite, make sure that ${GREEN}$byo_ccvm_service_account${RESET} has GCP IAM Role serviceAccountTokenCreator assigned and HCP Vault Role: ${GREEN}$hcp_vault_role_name${RESET} association"
            else
                echo "${YELLOW}**Warning**${RESET} - As a prerequisite, make sure that ${GREEN}$byo_ccvm_service_account${RESET} has IAM Role secretmanager.secretAccessor access to Secret Manager ${GREEN}$secret_name${RESET}"
            fi
            echo "export TF_VAR_byo_ccvm_service_account='$byo_ccvm_service_account'" >> .zsecrc
        break
        ;;
        no|n )
            if [[ $vault == "hcp" ]]; then
                echo "${GREEN}Terraform will create a new Service Account and assign role serviceAccountTokenCreator${RESET}"
                echo "${YELLOW}**Warning**${RESET} - Make sure that HCP Vault Role: ${GREEN}$hcp_vault_role_name${RESET} is not restricting access specific Service Accounts. \ 
Else, you will need to add this new service account to your HCP Vault before Cloud Connector will be able to retrieve secrets" 
            else
                echo "${GREEN}Terraform will create a new Service Account and assign role secretmanager.secretAccessor to $secret_name${RESET}"
            fi
        break
        ;;
        * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
        esac
    done

    http_probe_port_default=50000
    read -r -p "${CYAN}Enter CC service health probe TCP port number. Valid input = 80 or any number between 1024-65535 [Default=$http_probe_port_default]: ${RESET}" http_probe_port_input
    http_probe_port=${http_probe_port_input:-$http_probe_port_default}
    if ((http_probe_port == 80 || http_probe_port >= 1024 && http_probe_port <= 65535)); then
        echo "${GREEN}Valid HTTP probe port input of $http_probe_port${RESET}"
        echo "export TF_VAR_http_probe_port=${http_probe_port}" >> .zsecrc
    else
        echo "${RED}Invalid HTTP probe port value${RESET}"
        echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
        exit 1
    fi

    az_count_default=2
    if [[ "$dtype" == "base_1"* ]]; then
        echo "${GREEN}$dtype} will deploy resources in one Zonal Instance Group in $gcp_location${RESET}"
        echo "export TF_VAR_az_count=1" >> .zsecrc  
    else
        read -r -p "${CYAN}Enter how many Availability Zone subnets [1-3] to deploy across? [Default=$az_count_default]: ${RESET}" az_count_input
        az_count=${az_count_input:-$az_count_default}
        if ((az_count >= 1 && az_count <= 3)); then
            echo "${GREEN}$dtype will deploy Cloud Connectors across $az_count Zonal Instance Groups in $gcp_location${RESET}"
            echo "export TF_VAR_az_count=$az_count" >> .zsecrc
        else
            echo "${RED}invalid az_count value. Must be a number between 1 and 3${RESET}"
            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
            exit 1
        fi  
    fi


    cc_count_default=2
    if [[ "$dtype" == "base_1"* ]]; then
        echo "${GREEN}$dtype will deploy one Cloud Connector in $gcp_location${RESET}" 
        echo "export TF_VAR_cc_count=1" >> .zsecrc   
    elif [[ "$dtype" == *"ilb"* ]]; then
        echo "${GREEN}You have selected $az_count zones to deploy CCs to behind a Load Balancer${RESET}"
        read -p "${CYAN}Enter how many Cloud Connectors to deploy in each zone? [Default=$cc_count_default]: ${RESET}" cc_count_input
        cc_count=${cc_count_input:-$cc_count_default}
        if ((cc_count >= 1 && cc_count <= 10)); then
            echo "${GREEN}$dtype will deploy $cc_count Cloud Connectors in each [$az_count] Zonal Instance Groups in $gcp_location${RESET}"
            echo "export TF_VAR_cc_count=$cc_count" >> .zsecrc
        else
            echo "${RED}invalid cc_count value. Must be a number between 1 and 20${RESET}"
            echo "${YELLOW}Delete .zsecrc file and re-run zsec up...${RESET}"
            exit 1
        fi  
    fi

   min_replicas_default=2
    while [[ "$dtype" == *"asg"* ]]; do
        read -r -p "${CYAN}Enter the minimum number of Cloud Connectors to maintain per each Autoscale Instance Group [Default=$min_replicas_default]: ${RESET}" min_replicas_input
   min_replicas=${min_replicas_input:-$min_replicas_default}
        case $min_replicas in
        1|2|3|4|5|6|7|8|9|10)
        echo "Cloud Connector Minimum size: ${GREEN}${min_replicas}${RESET}"
        echo "export TF_VAR_min_replicas=${min_replicas}" >> .zsecrc
        break
        ;;
        *)
        echo "${RED}Invalid ASG Minimum size: ${min_replicas}. Enter a number 1-10${RESET}"
        ;;
        esac
    done

    max_replicas_default=4
    while [[ "$dtype" == *"asg"* ]]; do
        read -r -p "${CYAN}Enter the maximum number of Cloud Connectors to maintain per each Autoscale Instance Group [Default=$max_replicas_default]: ${RESET}" max_replicas_input
    max_replicas=${max_replicas_input:-$max_replicas_default}
        if [[ "$max_replicas" -lt "$min_replicas" ]]; then
            echo "${YELLOW}Max size must be greater than or equal to ${min_replicas}${RESET}"
        else
            case $max_replicas in
            1|2|3|4|5|6|7|8|9|10)
                echo "Cloud Connector Maximum size: ${GREEN}${max_replicas}${RESET}"
                echo "export TF_VAR_max_replicas=${max_replicas}" >> .zsecrc
            break
            ;;
            *)
                echo "${RED}Invalid ASG Maximum size: ${max_replicas}. Enter a number 1-10${RESET}"
            ;;
            esac
        fi
    done   

    target_cpu_util_value_default=80
    while [[ "$dtype" == *"asg"* ]]; do
        read -r -p "${CYAN}Enter desired ASG Target Tracking CPU % Utilization target [Default=$target_cpu_util_value_default]: ${RESET}" target_cpu_util_value_input
        target_cpu_util_value=${target_cpu_util_value_input:-$target_cpu_util_value_default}
        if [[ "$target_cpu_util_value" -lt 1 || "$target_cpu_util_value" -gt 100 ]]; then
            echo "${YELLOW}Target tracking percentage must be a number between 1-100${RESET}"
        else
            case $target_cpu_util_value in
            *) 
                echo "ASG CPU Utilization Target Value set to ${GREEN}${target_cpu_util_value}${RESET}"
                echo "export TF_VAR_target_cpu_util_value=${target_cpu_util_value}" >> .zsecrc 
            break
            ;;
            esac
        fi
    done

    while [[ "$dtype" == *"asg"* && "$oper" == "up" ]]; do
        echo "Zscaler Autoscaling requires Cloud Runction Code hosted in a GCP Storage Bucket..." 
        read -r -p "${CYAN}Do you have an existing Storage Bucket to use? (yes/no): ${RESET}" byo_bucket_response
        case $byo_bucket_response in 
        yes|y ) 
            echo "Using an existing Storage Bucket.."
            echo "export TF_VAR_byo_storage_bucket=true" >> .zsecrc
            read -r -p "${CYAN}Enter existing Storage Bucket Name (E.g zscc-bucket): ${RESET}" byo_storage_bucket
            echo "export TF_VAR_storage_bucket_name=$byo_storage_bucket" >> .zsecrc
            echo "${GREEN}You entered $byo_storage_bucketc${RESET}"
            read -r -p "${CYAN}Is the latest Cloud Function version ZIP file already uploaded to this bucket? (yes/no): ${RESET}" existing_zip_response
                case $existing_zip_response in 
                yes|y ) 
                    read -r -p "${CYAN}Enter source object name here (e.g. cloud-functions-latest.zip): ${RESET}" zip_manual_input
                    echo "export TF_VAR_cloud_function_source_object_name=$zip_manual_input" >> .zsecrc
                    echo "${GREEN}You entered $zip_manual_input${RESET}"
                    upload_function_zip=false
                    echo "export TF_VAR_upload_cloud_function_zip=false" >> .zsecrc
                break
                ;;
                no|n )
                    echo "${GREEN}We will try downloading the latest Cloud Function ZIP locally and upload to Storage Bucket $byo_storage_bucket...${RESET}"
                    upload_function_zip=true
                    echo "export TF_VAR_upload_cloud_function_zip=true" >> .zsecrc
                break
                ;;
                * ) echo "${RED}Invalid response. Please enter yes or no${RESET}";;
                esac
        break
        ;;
        no|n )
            echo "${GREEN}Script will create a new Storage Bucket and upload Cloud Function ZIP...${RESET}"
            echo "export TF_VAR_byo_storage_bucket=false" >> .zsecrc
            echo "export TF_VAR_upload_cloud_function_zip=true" >> .zsecrc
            upload_function_zip=true
        break
        ;;
        * ) echo "${RED}Invalid response. Please enter yes or no${RESET}";;
        esac
    done
    
    while [[ "$dtype" == *"asg"* && "$oper" == "up" && "$upload_function_zip == true" ]]; do
        for file in ./$dtype/function_zip/*.zip; do
            zip_lookup=$(basename ./$dtype/function_zip/*.zip)
            if [[ $zip_lookup == "*.zip" ]]; then
                echo "${YELLOW}Cloud Function ZIP file appears to be missing from directory ${dtype}/function_zip. Trying to download the latest stable version now...${RESET}"
                cloud_function_version=latest
                zip_name="cloud-functions-$cloud_function_version.zip"
                if [[ $cloud_function_version == "latest" ]]; then
                    URL=https://zscaler-cc-functions-artifacts.s3.amazonaws.com/zscaler-cc-functions/latest/$zip_name
                else
                    URL=https://zscaler-cc-functions-artifacts.s3.amazonaws.com/zscaler-cc-functions/releases/$cloud_function_version/$zip_name
                fi
                echo "${GREEN}Starting download of: $URL${GREEN}"
                echo "Saving as: $dtype/function_zip/cloud-functions-latest.zip"
                curl -# -o $dtype/function_zip/cloud-functions-latest.zip --fail --show-error  $URL
                # Check the exit status of curl
                if [ $? -eq 0 ]; then
                    echo "-------------------------------------"
                    echo "Download of Zscaler Cloud Function completed ${GREEN}successfully!${RESET}"
                else
                    echo "-------------------------------------"
                    echo "Error: Download of Zscaler Cloud Function ${RED}failed!${RESET}"
                    exit 1
                fi
                echo "export TF_VAR_cloud_function_source_object_name=$zip_name" >> .zsecrc
                echo "export TF_VAR_cloud_function_source_object_path='./function_zip/$zip_name'" >> .zsecrc
            else
                while true; do
                    read -r -p "${CYAN}Cloud Function ZIP file named $zip_lookup identified in directory $dtype/function_zip. Is this the correct ZIP to use? (yes/no): ${RESET}" zip_lookup_response
                    case $zip_lookup_response in 
                    yes|y )
                        zip_name=$zip_lookup
                        echo "${GREEN}Using $zip_name for deployment...${RESET}"
                        echo "export TF_VAR_cloud_function_source_object_name=$zip_name" >> .zsecrc
                        echo "export TF_VAR_cloud_function_source_object_path='./function_zip/$zip_name'" >> .zsecrc
                    break
                    ;;
                    no|n )
                        read -r -p "${CYAN}Copy ZIP file to $dtype/function_zip/ and enter filename here (e.g. cloud-functions-latest.zip): ${RESET}" zip_manual_input
                        file_check=./$dtype/function_zip/$zip_manual_input
                        if test -f "$file_check"; then
                            echo "${CYAN}ZIP name $zip_manual_input will be used...${RESET}"
                            zip_name=$zip_manual_input
                            echo "export TF_VAR_cloud_function_source_object_name=$zip_name" >> .zsecrc
                            echo "export TF_VAR_cloud_function_source_object_path='./function_zip/$zip_name'" >> .zsecrc
                        else
                            echo "${RED}ZIP file named $zip_manual_input does not exist. Please confirm filename and path are correct and re-run zsec...${RESET}"
                            exit 1    
                        fi
                    break
                    ;;
                    * ) echo "${RED}Invalid response. Please enter yes or no${RESET}";;
                    esac
                done
            fi
        break
        done
    break
    done

    if [[ "$dtype" == "cc"* ]]; then
    echo "Configure Networking Infrastructure..."
        while true; do
        read -r -p "${CYAN}Are you deploying to existing VPC Networks in $project_id? (yes/no): ${RESET}" byo_vpc_response
            case $byo_vpc_response in 
            yes|y ) 
                echo "Using an existing VPC..."
                echo "export TF_VAR_byo_vpc=true" >> .zsecrc
                byo_vpc=true
                read -r -p "${CYAN}Enter existing Management VPC name (E.g vpc-mgmt): ${RESET}" byo_mgmt_vpc
                echo "${GREEN}You entered $byo_mgmt_vpc${RESET}"
                echo "export TF_VAR_byo_mgmt_vpc_name=$byo_mgmt_vpc" >> .zsecrc

                read -r -p "${CYAN}Enter existing VPC name (E.g vpc-service): ${RESET}" byo_service_vpc
                echo "${GREEN}You entered $byo_service_vpc${RESET}"
                echo "export TF_VAR_byo_service_vpc_name=$byo_service_vpc" >> .zsecrc
            break
            ;;
            no|n )
                echo "${GREEN}Terraform will create new Mgmt + Service VPC, Mgmt + Service Subnets, Cloud Router, and NAT Gateways${RESET}"
                echo "export TF_VAR_byo_vpc=false" >> .zsecrc
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done
    fi

    # Query for existing subnet IDs if byo_vpc true
    if [[ "$byo_vpc" == "true" ]]; then
    echo "Attemping deployment to existing VPCs..."
        while true; do
        read -r -p "${CYAN}Are you deploying to existing subnets in each VPC? (yes/no): ${RESET}" byo_subnet_response
            case $byo_subnet_response in 
            yes|y ) 
                echo "${GREEN}Using existing subnets for Cloud Connector...${RESET}"
                echo "export TF_VAR_byo_subnets=true" >> .zsecrc
                read -r -p "${CYAN}Please enter the Mgmt VPC subnet name (E.g mgmt-vpc-subnet-mgmt): ${RESET}" mgmt_subnet
                echo "${GREEN}You entered $mgmt_subnet${RESET}"
                echo "export TF_VAR_byo_mgmt_subnet_name=$mgmt_subnet" >> .zsecrc
                read -r -p "${CYAN}Please enter the Service VPC subnet name (E.g service-vpc-subnet-service): ${RESET}" service_subnet
                echo "${GREEN}You entered $service_subnet${RESET}"
                echo "export TF_VAR_byo_service_subnet_name=$service_subnet" >> .zsecrc
            break
            ;;
            no|n )
                echo "${GREEN}Terraform will attempt to create new subnets in both $byo_mgmt_vpc and $byo_service_vpc${RESET}"
                echo "export TF_VAR_byo_subnets=false" >> .zsecrc
                byo_subnets=false
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done
    fi

    #Query for subnet creation range override
    if [[ "$byo_subnets" == "false" ]]; then
    subnet_cc_mgmt_default="10.0.1.0/24"
    subnet_cc_service_default="10.1.1.0/24"
        echo "${YELLOW}Existing VPCs selected, but subnets need created...${RESET}"
        echo "${YELLOW}By default, Terraform will create a new Mgmt Subnet with a CIDR range of $subnet_cc_mgmt_default and a new Service Subnet with a CIDR range of $subnet_cc_service_default${RESET}"
        while true; do
            read -r -p "${CYAN}Do you want to manually define the CC subnet CIDR ranges instead? (yes/no): ${RESET}" change_cc_cidr_response
            case $change_cc_cidr_response in 
            yes|y )
                echo "Configuring each Cloud Connector subnet range..."
                read -r -p "${CYAN}Please enter the Mgmt VPC subnet CIDR (E.g 10.2.0.0/24): ${RESET}" custom_cc_mgmt_subnet
                echo "${GREEN}You entered $custom_cc_mgmt_subnet${RESET}"
                echo "export TF_VAR_subnet_cc_mgmt='$custom_cc_mgmt_subnet'"
                read -r -p "${CYAN}Please enter the Service VPC subnet CIDR (E.g 10.2.1.0/24): ${RESET}" custom_cc_service_subnet
                echo "${GREEN}You entered $custom_cc_service_subnet${RESET}"
                echo "export TF_VAR_subnet_cc_service='$custom_cc_service_subnet'"
            break
            ;;
            no|n )
                echo "${GREEN}Terraform will attempt to automatically create new subnets in each VPC${RESET}"
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done 
    fi

    # Query for existing Cloud Routers if byo_vpc true
    if [[ "$byo_vpc" == "true" ]]; then
        while true; do
        read -r -p "${CYAN}Do your Mgmt and Service VPCs already have a Cloud Router associated? (yes/no): ${RESET}" byo_router_response
            case $byo_router_response in 
            yes|y ) 
                echo "${GREEN}Using existing Cloud Routers...${RESET}"
                echo "export TF_VAR_byo_router=true" >> .zsecrc
                byo_router=true
                read -r -p "${CYAN}Enter existing Mgmt VPC Cloud Router name (E.g mgt-vpc-router): ${RESET}" byo_mgmt_router_name
                echo "export TF_VAR_byo_mgmt_router_name=$byo_mgmt_router_name" >> .zsecrc
                read -r -p "${CYAN}Enter existing Service VPC Cloud Router name (E.g service-vpc-router): ${RESET}" byo_service_router_name
                echo "export TF_VAR_byo_service_router_name=$byo_service_router_name" >> .zsecrc
            break
            ;;
            no|n )
                echo "${GREEN}Terraform will attempt to create new Cloud Routers in each VPC${RESET}"
                echo "export TF_VAR_byo_router=false" >> .zsecrc
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done
    fi

    # Query for existing Cloud NAT Gateways if byo_vpc true
    if [[ "$byo_vpc" == "true" ]]; then
        while true; do
        read -r -p "${CYAN}Do you Mgmt and Service VPCs already have NAT Gateways? (yes/no): ${RESET}" byo_ngw_response
            case $byo_ngw_response in 
            yes|y ) 
                echo "${GREEN}Using existing NAT Gateways for Cloud Connector connectivity...${RESET}"
                echo "export TF_VAR_byo_natgw=true" >> .zsecrc
                read -r -p "${CYAN}Enter existing Mgmt VPC Cloud NAT name (E.g mgt-vpc-nat): ${RESET}" byo_mgmt_natgw_name
                echo "export TF_VAR_byo_mgmt_natgw_name=$byo_mgmt_natgw_name" >> .zsecrc
                read -r -p "${CYAN}Enter existing Service VPC Cloud Router name (E.g service-vpc-nat): ${RESET}" byo_service_natgw_name
                echo "export TF_VAR_byo_service_natgw_name=$byo_service_natgw_name" >> .zsecrc
            break
            ;;
            no|n )
                echo "${GREEN}Terraform will attempt to create new NAT Gateway resources in each VPC${RESET}"
                echo "export TF_VAR_byo_natgw=false" >> .zsecrc
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done
    fi

    if [[ "$dtype" == "cc"* ]]; then
        while true; do
            read -r -p "${CYAN}Enable Google Cloud DNS for ZPA? (yes/no): ${RESET}" zpa_response
            case $zpa_response in 
            yes|y ) 
                echo "${GREEN}Enabling Google Cloud DNS module...${RESET}"
                zpa_enabled=true
                echo "export TF_VAR_zpa_enabled=$zpa_enabled" >> .zsecrc
            break
            ;;
            no|n )
                echo "${GREEN}No ZPA enablement...${RESET}"
                zpa_enabled=false
                echo "export TF_VAR_zpa_enabled=$zpa_enabled" >> .zsecrc
            break
            ;;
            * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
            esac
        done 
    fi

    if [[ "$zpa_enabled" == "true" || "$dtype" == *"zpa" ]]; then
    array=()
    domain_names_map="'{ "
    counter=0
        while true; do
            read -r -p "${CYAN}How many Domain/FQDN application segments to add to Google Cloud DNS Forwarding Zones?: ${RESET}" domain_number
            if [[ $domain_number == 0 ]]; then
                echo "${RED}Invalid input. Please enter a whole number for the number of domains you will be adding...${RESET}"
            elif [[ $domain_number =~ ^[0-9]+$ ]]; then
                echo "$domain_number domains to enter..."
                break
            else
                echo "${RED}Invalid input. Please enter a whole number for the number of domains you will be adding...${RESET}"
            fi
        done
        for i in $(seq $domain_number); do
            read -r -p "${CYAN}Enter a single ZPA Domain/FQDN ending with a trailing dot ( e.g. gcp.company.com. ): ${RESET}" domain_name
            if [[ $domain_name = *" "* ]]; then
                echo "${RED}Spaces not allowed. Please enter only one domain at a time. Delete .zsecrc file and re-run zsec up...${RESET}"
                exit 1
            elif [[ $domain_name == '' ]]; then
                echo "${RED}Empty entries are not allowed. Delete .zsecrc file and re-run zsec up...${RESET}"
                exit 1
            elif [[ $domain_name == "." ]]; then
                echo "${RED}You entered '.' dot. While Azure does support this to forward all domain requests, this could have unintended consequences/compatibility issues with Azure services${RESET}"
            elif [[ $domain_name == "."* ]]; then
                echo "${RED}Invalid format. Domains cannot start with a dot (.). Delete .zsecrc file and re-run zsec up...${RESET}"
                exit 1
            elif [[ $domain_name == "*"* ]]; then
                echo "${RED}Invalid format. Domains cannot start with a star/wildcard (*). Delete .zsecrc file and re-run zsec up...${RESET}"
                exit 1
            elif [[ $domain_name != *"." ]]; then
                echo "${RED}Invalid format. Domains must end with a dot (.). Delete .zsecrc file and re-run zsec up...${RESET}"
                exit 1
            fi
            array+=("$domain_name")
            counter=$(( $counter + 1 ))
            domain_names_map+="appseg$counter: \"$domain_name\", "
        done
        domain_names_map+="}'"
        echo "export TF_VAR_domain_names=$domain_names_map" >> .zsecrc
    fi

    support_access_response_default="no"
    while true; do
        read -r -p "${CYAN}By default, an outbound VPC firewall rule is configured enabling Zscaler remote support access. Would you like to disable this rule creation? [Default=$support_access_response_default]: ${RESET}" support_access_response_input
        support_access_response=${support_access_response_input:-$support_access_response_default}
        case $support_access_response in 
        yes|y ) 
            echo "Outbound rule permitting Zscaler Support access will not be created"
            echo "${YELLOW}*** Caution: Zscaler Support may not be able to assist as efficiently if troubleshooting is required without this access${RESET}"
            echo "export TF_VAR_support_access_enabled=false" >> .zsecrc
        break
        ;;
        no|n )
            echo "${GREEN}Outbound rule permitting Zscaler Support access will be created${RESET}"
            echo "export TF_VAR_support_access_enabled=true" >> .zsecrc
        break
        ;;
        * ) echo "${RED}invalid response. Please enter yes or no${RESET}";;
        esac
    done
fi


 #add local bin directory to PATH
if ! grep -Fxq "export PATH=\${PATH}:\${PWD}/bin" .zsecrc; then
    echo 'export PATH=${PATH}:${PWD}/bin' >> .zsecrc
fi

# add deployment type to .zsecrc for future runs
if [[ "$oper" == "up" ]]; then
    echo "${GREEN}Updating .zsecrc with dtype of $dtype${RESET}"
    sed -i'' -e '/dtype/d' .zsecrc
    echo "export dtype=${dtype}" >> .zsecrc
fi

# initialize environment variables

. ./.zsecrc

# check for valid environment variables in .zsecrc
if [ -z "$TF_VAR_credentials" ] || [ -z "$TF_VAR_project" ]; then
    echo "${RED}GCP Access info is missing. Remove .zsecrc file and rerun $0 $1${RESET}"
    exit 1
fi

if [[ $dtype != "base" ]]; then
    echo "Checking Cloud Connector provisioning info"
  if [ -z "$TF_VAR_cc_vm_prov_url" ] || [ -z "$TF_VAR_http_probe_port" ]  || [ -z "$TF_VAR_ccvm_instance_type" ]; then
    echo "${RED}Cloud Connector provisioning info is missing. Remove .zsecrc file and rerun $0 $1${RESET}"
    exit 1
  fi
fi

echo "Download terraform binary for $ostype if not present..."
if [[ ! -e ./$dir/terraform ]]; then
    curl -o ./$dir/terraform_${tversion}_${arch}.zip https://releases.hashicorp.com/terraform/$tversion/terraform_${tversion}_${os_str}_${arch}.zip
    unzip ./$dir/terraform_${tversion}_${arch}.zip -d ./$dir
    rm -f ./$dir/terraform_${tversion}_${arch}.zip
fi

if [[ "$oper" == "do" ]]; then
    exit 1
fi

if [[ "$oper" == "up" ]]; then
    echo "${GREEN}Bringing up Cloud Connector cluster...${RESET}"
    TF_DATA_DIR=./.terraform ./$dir/terraform -chdir="$dtype" init
    if [[ "$AUTO_APPROVE" ]]; then
        TF_DATA_DIR=./.terraform ./$dir/terraform -chdir="$dtype" apply -auto-approve
    else
        TF_DATA_DIR=./.terraform ./$dir/terraform -chdir="$dtype" apply
    fi

elif [[ "$oper" == "destroy" ]]; then
    echo "${YELLOW}Destroying Cloud Connector cluster...${RESET}"
    TF_DATA_DIR=./.terraform ./$dir/terraform -chdir="$dtype" init
    if [[ "$AUTO_APPROVE" ]]; then
        TF_DATA_DIR=./.terraform ./$dir/terraform -chdir="$dtype" destroy -auto-approve
    else
      TF_DATA_DIR=./.terraform ./$dir/terraform -chdir="$dtype" destroy
    fi
    echo "Removing Terraform files and directories..."
    rm -rf bin
    rm -rf $dtype/terraform.tfstate*
    rm -rf **/.terraform/* && rm -rf **/.terraform*
    find . -type f -name '.terraform.lock.hcl' -delete
    rm -rf .terraform* && rm -f terraform.tfstate*
    rm -f *.pem && rm -f *.pem.pub
    rm -f name_prefix random_string
    rm -rf user.key user.crt
    rm -rf systems.json setup-*.tar
    rm -rf **/errorlog.txt
now=$(date +'%Y-%m-%d-%H_%M_%S')
    echo "archiving .zsecrc file to .zsecrc-${now}"
    cp .zsecrc .zsecrc-${now}
    rm -rf .zsecrc && rm -rf .zsecrc.bak
fi
